### ISSUE TITLE
Include contents of `Changelog.md` into Release Notes

### ISSUE THREAD

**Issue by LecrisUT** [spglib/spglib#472]
Should be straightforward to grep the lines from `Changelog.md` and push them to the release body. There would be some duplications of the entries, which we need to check how to handle.

Another related issue to investigate is how to provide the contents of the release notes for Fedora. I think I can at least set it up to use only the contents of `Changelog.md`, but the section header might get in the way, need to check how other projects generate that.

**Comment by LecrisUT** [comment]
Another package to check [`towncrier`](https://towncrier.readthedocs.io/en/stable/) used by `attrs`

**Comment by amkrajewski** [comment]
You can also consider reversing the pipeline by (1) writing your changelog directly to GitHub Releases and then (2) pipelining them your documentation with a Sphinx extension like `sphinx_github_changelog`. Saved me a lot of time.

Automatically appending (or rebuilding) your changelog from GitHub API in Actions is also straightforward in any language of choice. See [this little gist](https://gist.github.com/amkrajewski/314506de60886aa9bde31211d09d5a2d) for instance. That way you get full control.

**Comment by LecrisUT** [comment]
Interesting idea. The only issue is that there were plenty of missing GH releases, and I'm not sure how this would work with doing post-release fixes like spelling or such. The `nim` approach though is still very cryptic and I don't see an example in the `gist` about how to implement that in `.github/workflows/release.yml`

**Comment by amkrajewski** [comment]
Missing releases and fixes shouldn't be a problem since you can always recompile documentation from a `workflow_dispatch:` trigger in addition to your versioned tag triggers. You can also add older releases attached to git tags without setting them as the latest ones. When I had too many on my plate, I just incremented the header level using find&replace and released them under something like "Legacy Releases" attached to an older tag.

The `nim` code gist I linked was just an example I use in `nim`-based projects. You can quickly implement such string manipulations in any language like Python. If you wanted to grab and use it, you could just do something like in [this workflow](https://github.com/amkrajewski/nimCSO/blob/main/.github/workflows/documentation.yaml) by adding:
```yaml
changelog:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
       uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v1
       with:
         nim-version: '2.0.2'
         repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build documentation
       run: |
         nim c -r -d:ssl -d:changelogType=md -d:user=spglib -d:repo=spglib getChangelog           
```
